Repository linhnguyen-gt/mini-zalo-demo, pull requests merged in 2023-11, with the labels that each got.

#18 Make code store
  .eslintrc.js
  .gitignore
  src/common/constants/index.ts
  src/components/RequestStorePickerLocation.tsx
  src/hooks/useSelectorPlace.ts
  src/hooks/useSelectorStore.ts
  src/pages/cart/delivery.tsx
  src/pages/cart/store-picker.tsx
  src/redux/banner/Actions.ts
  src/redux/categories/PlaceholderActions.ts
  src/redux/categories/PlaceholderReducer.ts
  src/redux/categories/PlaceholderTypes.ts
  src/redux/placeholder/PlaceholderActions.ts
  src/redux/placeholder/PlaceholderReducer.ts
  src/redux/placeholder/PlaceholderTypes.ts
  src/redux/rootReducer.ts
  src/redux/store/Actions.ts
  src/redux/store/Reducer.ts
  src/redux/store/Types.ts
  src/state.ts
  src/types/store.ts
Labels: Dev Done

#23 #12 [ Notification ] Make code Notification
  src/common/constants/index.ts
  src/components/NotificationList.tsx
  src/components/layout.tsx
  src/components/skeletons.tsx
  src/hooks/useSelectorNotify.ts
  src/pages/notification.tsx
  src/redux/notification/Actions.ts
  src/redux/notification/Reducer.ts
  src/redux/notification/Types.ts
  src/redux/rootReducer.ts
  src/state.ts
  src/types/Notify.ts
  src/utils/icon.ts
Labels: Dev Done

#30 #6 [ Product ] Make code product
  src/common/constants/index.ts
  src/components/display/price.tsx
  src/components/product/item.tsx
  src/components/product/picker.tsx
  src/pages/index/product-list.tsx
  src/pages/index/recommend.tsx
  src/redux/cart/Reducer.ts
  src/redux/product/Action.ts
  src/redux/product/ProductReducer.ts
  src/redux/product/Reducer.ts
  src/redux/product/Types.ts
  src/redux/rootReducer.ts
  src/state.ts
  src/types/product.ts
  src/utils/convert.ts
  src/utils/icon.ts
  src/utils/product.ts
Labels: Dev Done

#31 #7 [ Categories ] Make code Categorie
  src/hooks/useSelectorCategories.ts
  src/pages/category.tsx
  src/pages/index/categories.tsx
  src/pages/index/index.tsx
  src/redux/category/Actions.ts
  src/redux/category/Reducer.ts
  src/redux/category/Types.ts
  src/redux/rootReducer.ts
  src/state.ts
  src/types/category.ts
  yarn.lock
Labels: Dev Done

#35 34 categories loading
  src/components/skeletons.tsx
  src/pages/index/categories.tsx
  src/redux/category/Reducer.ts
Labels: Dev Done

#41 #27 [Loading] Make code loading
  src/pages/cart/cart-items.tsx
  src/pages/cart/preview.tsx
  src/pages/cart/store-picker.tsx
  src/utils/local-storage.ts
Labels: Dev Done

#38 34 categories loading
  src/components/skeletons.tsx
  src/pages/index/categories.tsx
Labels: Dev Done

#42 #34 [ Seketon ] Categories loading
  .eslintrc.js
  src/components/skeletons.tsx
  src/pages/category.tsx
  src/pages/index/categories.tsx
  src/redux/category/Reducer.ts
Labels: Dev Done

#44 #32 feat: animation order success
  .vscode/settings.json
  src/css/app.scss
  src/global.d.ts
  src/pages/success/index.tsx
  src/static/thanks.gif
  yarn.lock
Labels: Done

#48 Make success page
  package.json
  src/components/RoutesWithTransition.tsx
  src/components/layout.tsx
  src/css/app.scss
  src/pages/success/index.tsx
  src/static/success.gif
  src/static/success.svg
Labels: Dev Done

#46 9 make cart delete item
  src/pages/cart/cart-items.tsx
Labels: Dev Done

#50 #43 choose time into cart
  src/pages/cart/time-picker.tsx
Labels: Dev Done

#47 #32 feat: transition page order success
  src/css/app.scss
  src/pages/success/index.tsx
Labels: reopen

#55 [ Bug ] Search #53
  src/components/RoutesWithTransition.tsx
  src/pages/search/inquiry.tsx
  src/redux/product/Reducer.ts
  src/types/product.ts
  src/types/search.ts
Labels: bug, Dev Done

#49 #40 feat: [ Categories ] Get product follow category_id
  src/hooks/useGetProductCategory.ts
  src/pages/category.tsx
  src/types/category.ts
Labels: reopen

#59 #58 [ Bug ] Fix bug all page
  .gitignore
  package-lock.json
  src/components/RoutesWithTransition.tsx
  src/redux/notification/Actions.ts
  yarn.lock
Labels: Dev Done

#65 [ Bug ] Search #53
  src/hooks/useSearchProducts.ts
  src/pages/search/result.tsx
  src/types/search.ts
  src/utils/product.ts
Labels: bug, Dev Done

#66 #51 feat: add tooltip all button
  src/components/product/quantity-picker.tsx
  src/components/tooltip.tsx
  src/pages/cart/cart-items.tsx
  src/pages/success/index.tsx
Labels: Dev Done

#67 fix [Bug] animation router
  src/components/RoutesWithTransition.tsx
  src/css/app.scss
Labels: bug, Dev Done

#69 [Cart] make fix button delete
  src/components/product/picker.tsx
Labels: bug, Dev Done

#70 [Bug] fix core loading
  src/css/app.scss
Labels: bug, Dev Done

#68 #51 fix: css and timeout tooltip
  src/components/tooltip.tsx
  src/pages/success/index.tsx
Labels: Dev Done

#72 52 add tooltip all button
  src/components/tooltip.tsx
Labels: reopen

#76 [ Bug ] Version 11 #74
  src/components/RoutesWithTransition.tsx
  src/components/navigation.tsx
  src/pages/cart/preview.tsx
  src/pages/cart/store-picker.tsx
  src/pages/success/index.tsx
Labels: bug, Dev Done

#83 [ Order ] make code history orders
  README.md
  index.html
  package.json
  src/common/constants/index.ts
  src/components/skeletons.tsx
  src/hooks/useSelectorPaymentMethod.ts
  src/pages/cart/index.tsx
  src/pages/cart/term-and-policies.tsx
  src/pages/cart/transfer.tsx
  src/redux/payment-method/Actions.ts
  src/redux/payment-method/Reducer.ts
  src/redux/payment-method/Types.ts
  src/redux/rootReducer.ts
  src/static/icons/favicon.png
  src/types/payment-method.ts
  src/utils/convert.ts
  zmp-cli.json
  zmp-template.json
Labels: Dev Done

#82 #52 feat: unmount and mount
  src/components/NotificationList.tsx
  src/pages/index/product-list.tsx
  src/redux/banner/Actions.ts
  src/redux/banner/Reducer.ts
  src/redux/category/Actions.ts
  src/redux/category/Reducer.ts
  src/redux/notification/Actions.ts
  src/redux/notification/Reducer.ts
  src/redux/notification/Types.ts
  src/redux/product/Action.ts
  src/redux/product/Reducer.ts
  src/redux/product/Types.ts
  src/types/Notify.ts
  src/types/product.ts
Labels: Dev Done

#88 #87 [ Bug ] Scroll to top
  src/pages/cart/cart-items.tsx
Labels: Dev Done

#92 #91 [ Frontend ] Remove Transition
  package.json
  src/components/RoutesWithTransition.tsx
  src/css/app.scss
Labels: Done
